### ISSUE TITLE
Add expiration date to housing protection popup

### ISSUE THREAD

**Issue by erinmcel** [antievictionmappingproject/covid-19-map#102]
So that viewers can see the expiration date

**Comment by clhenrick** [comment]
@erinmcel @azadag do we have expiration dates for all geographies that have expired or will be expiring? If so what is the column name?

**Comment by erinmcel** [comment]
For the US data, the column is "Earliest Date Expiration” and for the global data, it is “End Date”.

**Comment by clhenrick** [comment]
Thanks @erinmcel 

@azadag would it make sense to normalize these two columns to a generic column for the map to consume?

Also, given that there are 3 sub categories of protections, do we want to include expiration dates for each of those? At least for the U.S.? It seems like that might be more helpful for folks who are on the ground.

**Comment by erinmcel** [comment]
Yes to having the 3 categories for the US! I had forgotten about that. So then 3 for the US and 1 for beyond the US.

**Comment by clhenrick** [comment]
Great, then we just need to know what the 3 columns are for the U.S., and to make sure they're being pulled into CARTO as UTC timestamps.

**Comment by erinmcel** [comment]
Sounds good. Right now they have the same column header in the Google sheet, “end date”, which I don’t want to mess up. @azadag can we change those header titles to reflect the different types of policies, ie “moratorium_end_date”, “rent_relief_end_date” and “court_end_date”?

**Comment by bretthalperin** [comment]
I will add this to the re-design as well.
