### ISSUE TITLE
Need to replace update Rent Strike form fields

### ISSUE THREAD

**Issue by erinmcel** [antievictionmappingproject/covid-19-map#106]
The current Housing Justice Action popups need to reflect the revised form (https://docs.google.com/forms/d/1_H63vF1zfHQQZfEiL8A98Fs9nwJWXp9CEYgeVbgBvDc/edit). The relevant fields should be: 
"Are you participating in an housing justice action? What type of action?"
"When is your action taking place (when did it begin or will begin, when does it end)?"
"Why are you participation in a housing justice action (personal motivation, external factors)"
"Localization"
"What resources or networks exist to support housing justice mobilization in your city?"

**Comment by timhitchins** [comment]
@erinmcel I have blocked out time later this week to work on this project.  I can take a look at this then if it hasn't been resolved.

**Comment by erinmcel** [comment]
Great! Thanks Tim!

**Comment by timhitchins** [comment]
@erinmcel  Is the linked google sheet with the new fields you mentioned currently reflecting these fields? I am not seeing it here:
https://docs.google.com/spreadsheets/d/1rCZfNXO3gbl5H3cKhGXKIv3samJ1KC4nLhCwwZqrHvU/edit#gid=0
or to the linked CARTO dataset:
https://ampitup.carto.com/dataset/emergency_housing_actions

**Comment by erinmcel** [comment]
Ah! Okay I see the problem is that it’s in the raw data but not public data. I’ll fix that now.

**Comment by erinmcel** [comment]
Okay, fixed in https://docs.google.com/spreadsheets/d/1rCZfNXO3gbl5H3cKhGXKIv3samJ1KC4nLhCwwZqrHvU/edit#gid=0. Just need Carto to sync at it should reflect the same

**Comment by timhitchins** [comment]
Awesome. Thank you so much.  Will jump back on this as soon as I get a
chance.

**Comment by unixjazz** [comment]
@erinmcel: would it be possible to change the name of Column "A" from "Type" to "Strike_Type" so we maintain consistency across DBs as in: https://reclus.mapacovid19.online/api/hausjustice/json ?

**Comment by azadag** [comment]
I can implement at the upload to carto level...
________________________________

**Comment by unixjazz** [comment]
@azadag: thank you!  the plan is to send you a csv with the same fields (column names) w/ data from locations outside the US.

**Comment by azadag** [comment]
Ok right now I download from the Google sheets, would that change?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by unixjazz** [comment]
@azadag: I am not sure, but I do not think it will change any time soon. Meanwhile, I will send you the CSV and you can copy + paste onto the public Google sheet: https://reclus.mapacovid19.online/api/hausjustice/csv

**Comment by timhitchins** [comment]
I just submitted a PR for this issue: https://github.com/antievictionmappingproject/covid-19-map/pull/112

**Comment by timhitchins** [comment]
This issue can be closed and was addressed in #112
