### ISSUE TITLE
Proxy to hide api keys

### ISSUE THREAD

**Issue by jimboweb** [antievictionmappingproject/covid-19-map#109]
We need a proxy requester so our api keys aren't visible either on public source code or on the client side. Something like what's described here:

https://blog.mauriciorobayo.com/how-to-hide-your-front-end-api-keys-ck6jqvll900y3dfs11u3x96tn

**Comment by clhenrick** [comment]
@jimboweb generally API keys that are meant to be used for frontend applications will allow for whitelisting URLs and/or IP address ranges to help prevent them from being abused, so a proxy may not be necessary.

For example, with the Bing Maps API keys you can do this in the developer settings:
https://blogs.bing.com/maps/2018-05/Announcing-Enhanced-Security-for-Bing-Maps-API-Keys

![image](https://user-images.githubusercontent.com/161748/87489949-34b49580-c5f9-11ea-8664-e7be755ef043.png)

**Comment by jimboweb** [comment]
You're right. I've added the referrer rule. I still don't know if having the api key public is safe.

**Comment by jimboweb** [comment]
So I tried to do that. I put in `https://covid19.antievictionmap.com/*` in the referrer rule, but when I use it I get a 401 error. 

Do you know what I'm doing wrong?

**Comment by jimboweb** [comment]
OK never mind I figured it out. By default I'm using the Brave browser that doesn't send the referer header, so when I tried it in Brave it doesn't work but in Chrome it works fine. That's a use case we have to consider but most people don't use this browser so I can turn on the referrer security and it'll be fine.

**Comment by clhenrick** [comment]
@jimboweb you may also want to add a rule for the Bing API that allows for the Netlify previews to work, perhaps something along the lines of `*--suspicious-easley-8d2764.netlify.app/*`

**Comment by timhitchins** [comment]
@jimboweb ok to close this now that #117 is merged?

**Comment by jimboweb** [comment]
Yes.

**Comment by timhitchins** [comment]
Closing now that #117 is merged.
