### ISSUE TITLE
Improved Color Scheme

### ISSUE THREAD

**Issue by clhenrick** [antievictionmappingproject/covid-19-map#11]
Currently the pink / green diverging color scheme is a bit misleading, as it seems to imply positive or negative conditions of a policy, when in fact policies are much more complex.

From Elana:

> yeah, i'd like to think that through a little more with others' help! i know @dpsakaguchi was interested in comparing the strengths and weaknesses of different policies, but given that they address evictions at different points in the process, late rent fees, rent deferments and payment plans, and additional factors... a  color gradient might not be the best way to represent that, unless we come up with some kind of scoring/grading formula, which i'm not super keen on

We could experiment with more than two colors, either diverging or perhaps categorical, to more robustly reflect policies.

**Comment by theecrit** [comment]
Just a note to also bear in mind [color contrast ratios for accessibility compliance](https://webaim.org/resources/contrastchecker/).

**Comment by erinmcel** [comment]
Today we realized that there are 3 distinct types of protections: moratorium, court closure, and legal defense. Research folks are down to categorize the existing entries so that we could better visually distinguish if that makes sense.

**Comment by clhenrick** [comment]
Inspiration from the NY Times for a "stop light" color palette that is a bit more accessible:

![image](https://user-images.githubusercontent.com/161748/79935819-b2a63d80-840a-11ea-96f5-f2d5a55ed491.png)

Although in this palette red stands out the most, is that what we would want to highlight in our map (deficits)? Or would we want the green to be stronger to highlight positive aspects? Or weight them evenly in which case we probably shouldn't use red and green?

**Comment by theecrit** [comment]
@erinmcel "good, mediocre, on not yet passed" mixes metrics, no? Seems like there's factual (full protection [whatever that means], partial protection, no protection), and quality (good, mediocre, poor).

FWIW, the (WebAIM link color contrast checker)[https://webaim.org/resources/linkcontrastchecker/] accommodates three colors so would be a good tool to check against a11y.

**Comment by erinmcel** [comment]
@theecrit yes agreed! @azadag has come up with a better way to disaggregate textually.

**Comment by clhenrick** [comment]
@theecrit the WebAIM color contrast checker tool appears to be useful for evaluating the contrast of text & link text color against the background color that the element the text is on top of, not for evaluating accessibility of a color scheme for visualization. There are some data vis specific color tools out there that do evaluate color contrast for palettes used in graphics such as maps and charts, will look for them and follow up with links to them here.

**Comment by theecrit** [comment]
@clhenrick Yes, it's intended for link text specifically, but in a pinch can be used to evaluate the ratio between any three colors. My initial search didn't turn up something specific to a full palette, but I've since found one from [Deque](https://color-contrast-checker.deque.com/) and
[this accessible palette builder](https://toolness.github.io/accessible-color-matrix/) based on work from 18F.

**Comment by clhenrick** [comment]
Gotcha, thanks for clarifying @theecrit. 

The [Color Brewer tool](https://colorbrewer2.org/) has some accessible palettes predefined that we could use. We'll probably want either a diverging or sequential color palette for 3 classes that's limited by the "color blind safe" option selected. Or if you have suggestions for other accessible palettes that convey "poor", "okay", and "good" that would be super helpful.

One other consideration is that we'll be showing the colors with a transparency applied (so that the basemap can be seen underneath the data overlays), so they'll be slightly dimmer than normal. We should probably take that into consideration as well when choosing a new color palette.

**Comment by clhenrick** [comment]
implemented in #63
