### ISSUE TITLE
On mobile search results shrink map to 50% of viewport height

### ISSUE THREAD

**Issue by clhenrick** [antievictionmappingproject/covid-19-map#114]
When searching for a location on mobile, the map area is split to half of the height of the viewport.

I think this is because there is an event listener that responds to the Leaflet map popup open event which applies a class name that shrinks the map. This is so that the infowindow displays when a user taps on a data point on the map. Now it appears to be conflicting with the search implementation.

Screenshot:

![Screen Shot 2020-07-07 at 16 20 39](https://user-images.githubusercontent.com/161748/86854752-e1c56600-c06d-11ea-965c-46ea0d9f5e7d.png)

**Comment by timhitchins** [comment]
Closing because this was solved with #117
