### ISSUE TITLE
Add new Google Form for rent strikes & resistance actions

### ISSUE THREAD

**Issue by clhenrick** [antievictionmappingproject/covid-19-map#12]
Needs a data schema, and should use a similar implementation to the policies form & sheet.

**Comment by erinmcel** [comment]
We can add this link to the text box for those who want to enter rent strikes: https://forms.gle/QDRYxyhCyUGP5oAL9. The geocoder is ready. I can also set up a geocoder on the tenant protection form.

**Comment by erinmcel** [comment]
So an idea for text for the text box, minus color related things, is:

` Where United States officials
            <strong class="color-passed">have passed</strong> (or tenants are
            <strong class="color-yet-to-pass">working to pass</strong>)
            emergency tenant protections during the COVID-19 crisis. Global map
            coming soon!
          </p>
          <p>
            <a
              href="https://docs.google.com/forms/d/e/1FAIpQLSfHzR_SYO-wKfa3Abi9jDvZXCH3dsLgrkDj-9Rwm-3oRjDD9A/viewform"
              target="_blank"
              >Submit info about your rent strike here.</a
            >
</p>
<p>
            <a
              href="https://docs.google.com/forms/d/e/1FAIpQLSfHzR_SYO-wKfa3Abi9jDvZXCH3dsLgrkDj-9Rwm-3oRjDD9A/viewform"
              target="_blank"
              >Submit your eviction protection updates here.</a
            >
`
