### ISSUE TITLE
Remove grey stroke around 'Few Tenant Protections' Policy Strength

### ISSUE THREAD

**Issue by brett-halperin** [antievictionmappingproject/covid-19-map#167]
![image](https://user-images.githubusercontent.com/35778453/95883148-95fb1a80-0d48-11eb-8458-7c5706045894.png)

There is a grey border around 'few tenant protections' that I hope we can remove for consistent visual design.

**Comment by Shinh18** [comment]
I would like to work on this issue. 
Please assign it to me.
Thank you

**Comment by bretthalperin** [comment]
> I would like to work on this issue.
> Please assign it to me.
> Thank you

thanks so much! 

cc: @timhitchins

**Comment by Shinh18** [comment]
Hey @bretthalperin Can you label this issue as Hacktoberfest? Actually, it is part of my school assignment to submit PRs to solve issues in open source project while participating in Hacktoberfest

**Comment by bretthalperin** [comment]
@Shinh18 i think that worked but if not lmk!

**Comment by Shinh18** [comment]
Thankyou!

**Comment by brett-halperin** [comment]
@Shinh18 are you still interested in helping with this?

**Comment by Shinh18** [comment]
@brett-halperin I already linked a PR for this issue a month ago.
