### ISSUE TITLE
Info window text changes to better highlight evictions

### ISSUE THREAD

**Issue by erinmcel** [antievictionmappingproject/covid-19-map#172]
Can we change the first survey form title on the infobox from "Global Housing Protection Legislation" to "Evictions and Eviction Moratoriums." And can the second be changed from "Housing justice actions around the world" to "Housing Justice Actions and Landlord Harassment"?

What about changing the title of the map, which is super long, to "Covid-19 Housing Map"?

**Comment by erinmcel** [comment]
We can keep the name of the map as it is and just change the name of the surveys too.

**Comment by djbusstop** [comment]
I think this is done, since I merged #175
