### ISSUE TITLE
Layer Order

### ISSUE THREAD

**Issue by goldfarb** [antievictionmappingproject/covid-19-map#18]
If the geography layers (cities, counties, states) are deselected and then reselected, they appear in the order they are turned on.

The cities should be the top layer, the states the bottom layer, and counties in between.

**Comment by timhitchins** [comment]
PR #20 has the layers in this order.

**Comment by river-honer** [comment]
Hello :) I am making an MR for this.

**Comment by river-honer** [comment]
I'm not super familiar how you operate but I made a PR for this. I have manually tested. It's ready for review :)

**Comment by clhenrick** [comment]
Thanks @river-honer! We have a Trello board and a Slack group, if you're interested send me an email and I can talk with our group about adding you.

**Comment by clhenrick** [comment]
Related: here's the [open issue describing the Leaflet layers control z-index bug](https://github.com/Leaflet/Leaflet/issues/5201)

**Comment by clhenrick** [comment]
Resolved in #37
