### ISSUE TITLE
"Last updated" on protections map is inaccurate(?)

### ISSUE THREAD

**Issue by brett-halperin** [antievictionmappingproject/covid-19-map#197]
Hi everyone, in the pop up info window boxes on the protections map, it says "last updated Apr 20, 2021" for all of them. I just want to confirm that is accurate? If I recall correctly, that date was from my mock-up, but I am not sure that information is actually accurate. Apologies if this was corrected and I am getting this wrong. Thanks! 

<img width="301" alt="image" src="https://user-images.githubusercontent.com/35778453/160013358-40929e84-b958-4ce2-b9e8-9ba7baadd052.png">

**Comment by lisjak** [comment]
solved by #127 in the react repo
