### ISSUE TITLE
iframe embed for BARS site is not mobile responsive

### ISSUE THREAD

**Issue by erinmcel** [antievictionmappingproject/covid-19-map#26]
Current embed with hash is: iframe width="600px" height="600px" src="<https://antievictionmappingproject.github.io/covid-19-map/#lat=37.8&lng=-122.45&states=false&rentstrike=true&z=11">/iframe 

Need to make it mobile responsive, particularly as the width is too wide right now.

Might need 100% width and explicit height

**Comment by clhenrick** [comment]
[Example responsive iframe embed](https://gist.github.com/clhenrick/aa325ea3bcc72371bfca7d9a51273fa4) for reference.
