### ISSUE TITLE
Need to add link to resources in the text box

### ISSUE THREAD

**Issue by erinmcel** [antievictionmappingproject/covid-19-map#27]
We could add these:

For tenants rights resources from Tenants Together, [click here. ](https://docs.google.com/document/d/1G-n_wK1JXuNHc2drqFjq3JdY-8ILG343zvbM5q8Ykx8/edit?fbclid=IwAR2A2royDMtVAM6b6yYM5GkMGhwmD0Lm5Ploz2lDcL2jIBpqxJ3OkebAef0)

For resources on rent striking, [click here](https://thenewinquiry.com/rent-strike-2020/).

**Comment by clhenrick** [comment]
added in #32
