### ISSUE TITLE
iframe embed breaks on desktop

### ISSUE THREAD

**Issue by clhenrick** [antievictionmappingproject/covid-19-map#38]
The iframe embed in [Bay Area Rent Strike breaks / is janky](https://bayarearentstrike.org/) when viewing the BARS site on desktop with the title content box expanded:

![image](https://user-images.githubusercontent.com/161748/79059439-e4f7b400-7c2e-11ea-9907-fc8a678383cb.png)

Right now I think we have a CSS `max-height` set on the title box and `overflow-y: auto` for the `div` that holds the content, but only on mobile. Applying similar properties for viewports > mobile would probably fix this.

**Comment by river-honer** [comment]
I will take a peek in to this today.

**Comment by river-honer** [comment]
I made an MR which fixes this problem without having to drown in mediaqueries, and which makes the vertical size of the info container on the left more consistent :)

**Comment by clhenrick** [comment]
Thank you @river-honer! Will take a look sometime today or tomorrow.

**Comment by c-i-v-i-m** [comment]
I finally got around to checking this out. I don't love the hardcoded pixel-based max height in the proposed solution, hardcoded scroll property for details elements.

Tried to give it a go keeping things as simple as possible: https://github.com/antievictionmappingproject/covid-19-map/pull/42

**Comment by river-honer** [comment]
I liked your solution. Left one comment about scrolling.

**Comment by clhenrick** [comment]
Fixed via #42
