### ISSUE TITLE
Add global data to the map

### ISSUE THREAD

**Issue by erinmcel** [antievictionmappingproject/covid-19-map#40]
The global data is being compiled, but we need to find a way to integrate it into the map. We should figure out if we want to change the tenant protection form itself to take country information, or if there should be two forms, one for the US and one for beyond the US.

**Comment by erinmcel** [comment]
We also want to add a way for folks to add local orgs and their websites

**Comment by clhenrick** [comment]
Noting that we still need to scope & define what "global data" means, how the data is handled compared to existing U.S. data, and to determine any UI/UX needs.

**Comment by c-i-v-i-m** [comment]
Do you have any particular considerations in mind. Some things I recall from our call:
- LTR vs RTL
- Date I18n
- Pluralization

- New content creation process (copywrite -> translate -> release vs. copywrite -> release -> translate)
- Dictionary editing (translation workflow: do we want the dictionary to only be editable by devs or provide some sort of access to translators?)

Perhaps, we can start by establishing a list of countries we want to target first and strategize from there? Like, maybe we don't need RTL right away if we don't have any organizers in Arabic speaking countries. Selecting a few countries to target and looking at sample data from those countries could also help us figure out what kind of data structures we want to work with?

**Comment by clhenrick** [comment]
@c-i-v-i-m I think we should tackle the issue of i18n separately from integrating global data. For this feature, we're focusing on adding data to the map for other countries. Language translation will be needed, but I think it's worth discussing separately. See issue #16

**Comment by river-honer** [comment]
I'm currently working on this issue. Adding the global states and provinces layer, and nations.
