### ISSUE TITLE
Markers not showing up when zoomed out

### ISSUE THREAD

**Issue by erinmcel** [antievictionmappingproject/covid-19-map#46]
When we zoom out, you can only see Guam for instance if you scroll right (east), not if you scroll left (west). Does it make sense to constrain the parameters and zoom more?

![Screen Shot 2020-04-21 at 7 44 10 PM](https://user-images.githubusercontent.com/8007917/79935026-bb960f80-8408-11ea-946f-9c873990d4f4.png)

**Comment by river-honer** [comment]
Hey @erinmcel I made a fix for this with the ideas you had to constrain the bounds and put a min zoom, there's some example screens in the PR.

**Comment by erinmcel** [comment]
Amazing @river-honer !
