### ISSUE TITLE
Marker clusters can be confusing to users

### ISSUE THREAD

**Issue by timhitchins** [antievictionmappingproject/covid-19-map#58]
(Note this issue is tangentially related to PR #60 (originally #53) and this issue may be addressed there.)

Per user feedback, the marker clusters are confusing for these reasons:
- Numbers in the markers don't make sense.
- Users are not sure what the markers and their colors actually represent.  (Note that #60 will update the color of the icons and the markers to be the same color.  This may partially address the color critique) 

![image](https://user-images.githubusercontent.com/10737214/80756617-b9f2d880-8ae7-11ea-851b-b15a480853d6.png)

**Comment by c-i-v-i-m** [comment]
I'm somewhat confused by the users' confusion. As far as I can tell, the numbers correctly capture the number of strike actions. Do we just need a more visual legend? "Circle = multiple strike actions (click to expand), House = strike action" (but we actually use the icons). 

Is the issue the maxClusterRadius?

**Comment by timhitchins** [comment]
@c-i-v-i-m This was brought up in our meeting today.  I think the main issue was that the variations of colors of the cluster icons in addition to the colors of the rent strike icons confused users.  On top of that they weren't sure if the numbers in the marker clusters represented something different that the number of clustered points.   IMO I believe that your #53 will solve the confusion because of the use of a single color.  In the future (after this push) we can add more detail to the legend to really make it clear.

**Comment by c-i-v-i-m** [comment]
@timhitchins  ok sweet. Let's wait until #53 rolls out an reassess then.

**Comment by timhitchins** [comment]
Sounds good @c-i-v-i-m.

**Comment by clhenrick** [comment]
Currently we're looking to use an orange / orange-red color for the rent-strike markers:

![Screen Shot 2020-05-05 at 1 15 11 PM](https://user-images.githubusercontent.com/161748/81135360-b1960580-8f0c-11ea-83a3-badd1d3d45f0.png)

Unfortunately this color is not great in terms of color contrast with a white / light background for a11y:

![image](https://user-images.githubusercontent.com/161748/81135406-e609c180-8f0c-11ea-85d7-10fbcc6a412f.png)

If we darken it slightly:

![Screen Shot 2020-05-05 at 1 15 26 PM](https://user-images.githubusercontent.com/161748/81135414-f02bc000-8f0c-11ea-9980-994edae6762b.png)

we get improved color contrast and meet the WCAG AA rating for color contrast:

https://user-images.githubusercontent.com/161748/81108286-555fc100-8ecd-11ea-8d54-71c2f1144163.png

so I'm inclined to use the slightly darker color, but still need to see how it stands out on the new choropleth / policy score color scheme in #55

**Comment by clhenrick** [comment]
Hopefully #60 helps reduce confusion. We could also discuss implementing another form of spatial aggregation then clustering, but for now I think what we have done is an improvement so am closing this.
