### ISSUE TITLE
Map Layers are slower to load now

### ISSUE THREAD

**Issue by clhenrick** [antievictionmappingproject/covid-19-map#61]
After integrating the global data in #54 I've noticed that the map layers take a little longer to load. I suspect this may be due to the larger tables we're now using in Carto for geographic administrative boundaries that are based on Natural Earth data, which are quite big by default.

A few things we could do to help this:

- [ ] 1. Remove extra columns in the global countries and states/provinces tables that we don't need in the map. Currently we are just using a few columns such as the_geom, iso, name, etc. All others could probably be removed to make the table size smaller, but we should double check to make sure there are not other columns we may want to keep for the future (i18n comes to mind).

- [x] 2. Add a loading indicator somewhere to the map to give the user feedback that the map is loading. This would be especially helpful for folks on slower network connections.

- [ ] 3. Lazy load layers: Instead of loading all layers ~~at once in a `Promise.all()`~~ on the map's first render, we could only load layers that are enabled in the layer control and URL hash. This would make iframe embeds of the map that only have a specific layer or two enabled load faster as well. 

- [x] 4. Move the Rent Strikes data to Carto. This data layer takes the longest to load, likely because it's coming from a Google Sheets CSV export URI, and moving it to Carto would likely result in a faster fetch request. We'll need the data in Carto anyway for doing other things later, such as searching by a user's location or filtering by the browser's viewport bounding box.

Open to other ideas as well.

**Comment by timhitchins** [comment]
It's worth also noting that the CARTO SQL docs include some query optimization tips:
https://carto.com/developers/sql-api/guides/query-optimizations/

The main suggestion in the docs is to create indexes, which we should probably do in addition to the other suggestions.
https://www.postgresql.org/docs/11/sql-createindex.html

**Comment by clhenrick** [comment]
+1 on creating indexes. I thought Carto did this by default when importing
new data but perhaps not.

-Chris
clhenrick.io

**Comment by timhitchins** [comment]
@clhenrick I am no expert, but it seems to me that only half of the loading time is spent on the CARTO requests and the rest of the time is spent on client side geojson processing (the big gap is after the CARTO responses). 
![image](https://user-images.githubusercontent.com/10737214/81256541-abc02300-8fe5-11ea-8600-3abe9f77f567.png)

I already tested out a solution for a loading indicator that works.  Any thoughts on starting a new PR to implement it or do we want to hold off on PR's until #28 is merged?

**Comment by clhenrick** [comment]
@timhitchins thanks! I think you may be right, when I looked at the performance tab in Firefox it looks like a lot of style changes, paints, and garbage collection. Most of this time is spent in`handleData()`

![Screen Shot 2020-05-07 at 9 18 59 AM](https://user-images.githubusercontent.com/161748/81319029-f07aa700-9043-11ea-8740-ec3d27a3fa53.png)

![Screen Shot 2020-05-07 at 9 19 26 AM](https://user-images.githubusercontent.com/161748/81319045-f4a6c480-9043-11ea-9adc-c51a98e7e657.png)

**Comment by clhenrick** [comment]
@timhitchins also thanks for looking into the loading indicator, let's table it for now until we can get #28 in if that sounds good to you?

**Comment by timhitchins** [comment]
Sounds good @clhendrik.  I will look more into the performance tab in
Firefox as well.  I was looking for the right tool to get the detail you
found.

**Comment by timhitchins** [comment]
I am gonna start to work on part 2 of this issue.  I know that #76 is still not merged into master, and that it addresses other aspects of this issue, but a loading screen/icon will still benefit slower networks.

> Add a loading indicator somewhere to the map to give the user feedback that the map is loading. This would be especially helpful for folks on slower network connections.

**Comment by clhenrick** [comment]
@timhitchins thanks, I just merged #76 so feel free to branch off from master to grab those changes

**Comment by timhitchins** [comment]
Part 2 of this issue was addressed with #81.

**Comment by timhitchins** [comment]
Closing this issue based on out clean up talk today in the dev meeting.  Will be addressed in the design update.
