### ISSUE TITLE
Infowindows missing Resources link for national protections data

### ISSUE THREAD

**Issue by erinmcel** [antievictionmappingproject/covid-19-map#66]
It is currently not showing up, but was before. It is showing up for US data.

**Comment by clhenrick** [comment]
@erinmcel this makes me think that now that we have the [PR build previews via Netlify](https://deploy-preview-28--suspicious-easley-8d2764.netlify.app/) (also see [my Slack note about this](https://antievictionmap.slack.com/archives/C0101NLTHHB/p1588809939129200)), we can (and probably should) ask non-dev folks to take a look at any new changes before they are made live. This way we can have a better chance of spotting anything wrong before new changes go into effect, by having more eyes on pending updates.

**Comment by erinmcel** [comment]
I like this idea! I’ll better familiarize myself with it now.

**Comment by clhenrick** [comment]
@erinmcel do you know what field in the sheet or Carto table this is?

**Comment by clhenrick** [comment]
@erinmcel looks like the values for the link field aren't being included with the data in Carto. 
@azadag would you maybe check to make sure that they're being included?

**Comment by river-honer** [comment]
Solved
