### ISSUE TITLE
Need to include geographies that have expired

### ISSUE THREAD

**Issue by erinmcel** [antievictionmappingproject/covid-19-map#67]
We don't always know the expiration date, and currently places that might have expired (but might not have as the dates change frequently) are missing on the map (ie. Massachusetts). Perhaps  we could show these as cross hatched.

**Comment by clhenrick** [comment]
[Here's a prototype](https://observablehq.com/d/b7668b4a880426ac) showing how we might visualize policies that have expired using a pattern fill that uses the same color as the existing / non-expired policies.

Example showing states:
![image](https://user-images.githubusercontent.com/161748/83083249-82217700-a03a-11ea-885f-e5c4ee1c4ba5.png)

**Comment by clhenrick** [comment]
Just noticed that something seems to be causing the pattern fills to not render on iOS Safari:

![image](https://user-images.githubusercontent.com/161748/83185626-1f82b680-a0e0-11ea-9ec7-08c7fc7a9f3c.png)

We’ll have to debug this before implementing it

**Comment by clhenrick** [comment]
@azadag do you know what field we'll reference in the protections data to determine if a protection has expired or partially expired?

**Comment by erinmcel** [comment]
@azadag merged the three expiration columns to create a 4th that lists the earliest expiration date. Column AZ.

**Comment by clhenrick** [comment]
@erinmcel thanks, is the column name literally called "AZ"?

**Comment by erinmcel** [comment]
Oh no! Sorry. "Earliest Date Expiration"

**Comment by erinmcel** [comment]
And this is only for the US data. For the global data, there is only one column for expiration dates, called "End Date". In both tables (US and non-US), there are some entries in which we don't know expiration dates. They are current coming up as #N/A in the US data and as blank in the global data. Happy to change this if that makes sense.

**Comment by azadag** [comment]
Chris,

I'll export it as earliest_date_expiration...

**Comment by clhenrick** [comment]
To keep the client side handling of this simple, we'll want a single field in the Carto table that we can use to identify whether or not a geography has an expired protection. 

@azadag thanks, what will the data type be for `earliest_date_expiration` ?

**Comment by azadag** [comment]
whatever the date import type for carto works out to be?

**Comment by clhenrick** [comment]
@azadag I guess I'm wondering if it would make sense to have this field be a Boolean for simplicity sake. If it's a timestamp then we get into having to 1. converting the timestamp string into a Date object, and then doing UTC date comparison stuff for each geography to see if it is expired or not. IMO that's something that could just be done on the "backend" when running the script so that the client can have a yes/no for expired protections, rather than having to figure it out on the fly. I suppose the downside to this approach is that we would probably need to be running the script daily to make sure such a Boolean expired column stays up to date.

**Comment by azadag** [comment]
yes that makes sense too. I updated the output to do that. will be synced soon.

**Comment by azadag** [comment]
ok field: _earliest_date_expiration_bool_ 
Current if law is still in place,
Expired if expired.

**Comment by azadag** [comment]
hmm do you have guidance for international date-time? or should i not complicate it?

**Comment by clhenrick** [comment]
@azadag I think it's usually best to store international datetime in UTC
