### ISSUE TITLE
Add placeholder for missing Summary field in Infowindows

### ISSUE THREAD

**Issue by clhenrick** [antievictionmappingproject/covid-19-map#69]
Relates to #68 

Placeholder text should be: "Policy summary coming soon."

**Comment by erinmcel** [comment]
These are now all filled in with summaries

**Comment by clhenrick** [comment]
Still a good idea to have a fallback one IMO, and potentially for other data fields as well to make the infowindows look more consistent from place to place. Maybe making a separate issue / Trello card would be a good idea.

**Comment by timhitchins** [comment]
This issue has been addressed and can be closed per confirmation in the dev meeting.  Can make a separate issue if necessary.
