### ISSUE TITLE
Distinguish counties from cities

### ISSUE THREAD

**Issue by erinmcel** [antievictionmappingproject/covid-19-map#7]
We could make counties squares or triangles, and perhaps slightly larger. It would be great too if counties could be lower on the z-index, so that it is apparent that cities are contained within them.

**Comment by clhenrick** [comment]
Adding a legend would be good as well, so that people understand what the different shapes mean.

**Comment by clhenrick** [comment]
Alternatively we could (and probably should) render counties as polygons, not as points. This is especially important for counties that cover large geographic areas, such as Los Angeles County.

**Comment by goldfarb** [comment]
[initial fix](https://github.com/antievictionmappingproject/covid-19-map/tree/counties)
Separated the cities & counties. For the time being, I used circles for the counties as well, as other shapes were hectic visually.

**Comment by clhenrick** [comment]
Fixed in #36
