### ISSUE TITLE
Country and state name not showing in infowindow jurisdiction name

### ISSUE THREAD

**Issue by river-honer** [antievictionmappingproject/covid-19-map#70]
The name of the jurisdiction is passed to the infowindow handlebars template with the `jurisdictionName` property. For all cities, the infowindow is only showing the city name.

We need to make sure that:
1. The query for each city should include the state and country name fields
2. When getting the props from the results in the `handleCitiesLayer` function, we should make sure we are accessing the correct name. Currently we are using `properties.Country` but this may be wrong, since the data model could have changed to use `properties.country`. 

It would be good to make sure all of the correct names are being queried and passed in to the name building template string for each layer.

**Comment by clhenrick** [comment]
Fixed via #28
