### ISSUE TITLE
Implement state management

### ISSUE THREAD

**Issue by timhitchins** [antievictionmappingproject/covid-19-map#78]
As this app grows we will need to eventually include some process for managing state.  Conversations regarding future ui frameworks have revolved around including vue.js, which has its own state management. But there is no certainty for when this will be implemented.   In the meantime we need to consider another process that will be simple and not require a great deal of refactoring later, perhaps a pubsub as suggested by @clhenrick?

cc @river-honer @jimboweb @goldfarb

**Comment by timhitchins** [comment]
@clhenrick now that we have `d3.dispatch` and the pubsub about to get merged into any objections to closing this?

**Comment by clhenrick** [comment]
@timhitchins yeah I think we're good for now, closing.
