### ISSUE TITLE
Most recent submissions for existing geographies should replace or overlay existing ones

### ISSUE THREAD

**Issue by erinmcel** [antievictionmappingproject/covid-19-map#8]
We are getting multiple submissions for similar geographies, ie. the state of Oregon. It would be great if the most recent submission could be visible one, as things change quickly and the most recently added submission will likely reflect the current state of things.

**Comment by sraby** [comment]
From trello 

> data maintainers / validators would be de-duplicating multiple entries for similar geographies

https://trello.com/c/a8P4qgpd/13-most-recent-submissions-for-existing-geographies-should-replace-or-overlay-existing-ones
