### ISSUE TITLE
Change the wording and description of "rent strike" in the text box

### ISSUE THREAD

**Issue by erinmcel** [antievictionmappingproject/covid-19-map#80]
Perhaps to: “Fill  out to submit information about: Organizing, resistance, and mutual aid in the form of rent strikes, housing reclamation, solidarity work, squats, and more. Also fill out if you are looking for solidarity and resources to help cancel rent.”

(This rewording comes from conversations with community partners in the US and globally alike.)

**Comment by timhitchins** [comment]
@erinmcel To clarify:  we need to change the part that says "Where organized rent strikes are currently occurring or may be occurring" to the text you suggested right? 
![image](https://user-images.githubusercontent.com/10737214/82763141-5728f000-9dba-11ea-95f4-fe9ccd75d97a.png)

**Comment by erinmcel** [comment]
Thanks! This is something that @unixjazz has also been thinking through: https://antievictionmap.slack.com/archives/C012KH48SMP/p1590023278092900. Sound like instead of “rent strike,” we’re thinking of expanding the category to “housing justice action."
