### ISSUE TITLE
State and county labels in wrong place on Android Chrome

### ISSUE THREAD

**Issue by jimboweb** [antievictionmappingproject/covid-19-map#83]
To reproduce:
- in Chrome on Android phone load map
- turn sideways to get landscape mode
- turn back to portrait mode
- click on a county or state

problem: label for county or state appears several hundred pixels above the county or state you clicked on .

**Comment by clhenrick** [comment]
I suspect this may be related to how we determine whether or not a viewport is small enough for a mobile device (see `src/constants.js`).

**Comment by timhitchins** [comment]
Bug was addressed by @jimboweb .
