### ISSUE TITLE
Add data disclaimer to map

### ISSUE THREAD

**Issue by clhenrick** [antievictionmappingproject/covid-19-map#86]
e.g.

> DISCLAIMER: This data is by no means perfect or exhaustive of all emergency tenant protection policies ~~in the United States and elsewhere~~. It has been crowdsourced and is maintained by a team of dedicated volunteers. If you notice something missing or incorrect in the data, please reach out to us to let us know so we may update it accordingly!

cc @erinmcel does this look good?

**Comment by erinmcel** [comment]
Looks good to me! Thanks for this. Not sure if we need the US and elsewhere?
