### ISSUE TITLE
Update deploy script to include repo

### ISSUE THREAD

**Issue by clhenrick** [antievictionmappingproject/covid-19-map#87]
**Update (06/15/2020)** the site is now being served using Netlify which creates a build from master (any merge to master will update the build). However, we still have the https://antievictionmappingproject.github.io/covid-19-map/ URL serving the site as well. We should probably deprecate the latter at some point, but don't want things to break so are keeping it for now. 

---

For folks who have write access to this repo but have forked the repo to their own account, the `deploy` script will push to the `gh-pages` branch of their _forked repo, not this one._ To fix this we can [add an option for the repository to deploy to](https://www.npmjs.com/package/gh-pages#optionsrepo)

So I think the script should be updated to be something like the following in `package.json`:

```
deploy: "npm run build && gh-pages -d dist -r 'https://github.com/antievictionmappingproject/covid-19-map.git'"
```

... but need to fork the repo and test this to make sure. cc @timhitchins

**Comment by timhitchins** [comment]
Thanks for looking in this @clhenrick.  Looking at the linked docs, this does seem like the appropriate solution.

**Comment by clhenrick** [comment]
No worries @timhitchins and feel free to tack this on to another PR.

I believe Netlify also deploys automagically when we push to master. If we ever end up buying a TLD name we can hook it up to Netlify (or Github Pages obviously).

**Comment by timhitchins** [comment]
I tested this out and it worked as expected.  Just needs a PR or tacked on to another PR now.
cc  @clhenrick

**Comment by clhenrick** [comment]
Now that we're hosting the site using a custom subdomain we'll need to make sure that the CNAME file doesn't get deleted (or is recreated) whenever we deploy the site.

One way of doing this would be to `git cherry-pick 25d4099` the commit that created the CNAME file. 

We may have to write our own `.sh` script to do this, not sure if the `gh-pages` npm package is capable of doing this or not.

**Comment by clhenrick** [comment]
Probably an easier way to do this would be to add the CNAME file to master branch and then have Webpack copy it over to the `dist` directory using the `CopyWebpackPlugin` (this plugin is [already being used to copy over static assets](https://github.com/antievictionmappingproject/covid-19-map/blob/master/webpack.config.js#L242-L244), so should be simple to modify). 

The contents of the CNAME file should be a single line containing:

```
covid19.antievictionmap.com
```
