### ISSUE TITLE
Move rent strikes data to Carto

### ISSUE THREAD

**Issue by clhenrick** [antievictionmappingproject/covid-19-map#90]
This issue is related to making the layers load faster (#61) and for the search feature we’re planning to implement. 

Getting rent-strikes data into Carto requires a similar approach to how the evictions protections data is synced with Carto from a sheet in Dropbox. We'll also need to update how the data is fetched in `data.js` and have an SQL query in `queries.js`.

@azadag any chance you could write another ETL script that could do this? We could run it on a cron job or whenever we update the protections data. Let me know if you have thoughts.

**Comment by azadag** [comment]
carto link is here: https://ampitup.carto.com/dataset/emergency_housing_actions

**Comment by clhenrick** [comment]
Thanks @azadag !
