### ISSUE TITLE
Need to add accreditation info somewhere

### ISSUE THREAD

**Issue by erinmcel** [antievictionmappingproject/covid-19-map#91]
There are some researchers and community groups whose policy descriptions and research we are incorporating into the map that we should credit somewhere. Off the top of my head, these include: Tenants Together, East Bay Housing Organizations, Community Justice Project, and Emily Benfer at Columbia University. 

There are also community partners who we're working with that would be nice to list somewhere, such as: Mapping Action Collective, kollektiv orangotango, Bay Area Rent Strike, and European Action Coalition for the Right to Housing, and the Center for Critical Internet Inquiry 

Then there are groups that we're consulting with around our policy scoring such as Right To The City Alliance, San Francisco Anti-Displacement Coalition, Policy Link, Lisa Bates at Portland State University, John Pollock from Public Justice

**Comment by clhenrick** [comment]
Maybe this information should go in a separate “credits” page or section? Do we want to link to each partner’s website?

**Comment by erinmcel** [comment]
Yes, that makes sense! If it's easier for now, I could just make this page on our main site and then we could link to it from the text box. It could be more incorporated into Brett's redesign later too if that makes sense.

**Comment by clhenrick** [comment]
That sounds like a good temporary solution, and yeah I think it would make sense to have a separate page to credit the community partners and other affiliates (cc @bretthalperin ).

**Comment by bretthalperin** [comment]
Makes sense, I will incorporate this in the next iteration.

**Comment by erinmcel** [comment]
How about just linking to this for the time being at the bottom of the text box? https://antievictionmap.com/covid19-global.

**Comment by djbusstop** [comment]
@erinmcel do you think the link should be displayed right after the header, or down at the bottom?

**Comment by erinmcel** [comment]
I think bottom would be fine!
